//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aural_Novel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Book
    {
        public int bookid { get; set; }
        public string bookname { get; set; }
        public string booklang { get; set; }
        public string booktype { get; set; }
        public Nullable<decimal> bookprice { get; set; }
        public string bookpic { get; set; }
        public Nullable<bool> isnew { get; set; }
        public Nullable<int> sellerid { get; set; }
        public byte[] bookaudio { get; set; }
        public byte[] booktrailer { get; set; }
    
        public virtual Seller Seller { get; set; }
    }
}
