//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aural_Novel.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Reader
    {
        public int rid { get; set; }
        [Required(ErrorMessage = "Enter your first name")]
        [Display(Name = "First Name")]
        public string rfname { get; set; }
        [Required(ErrorMessage = "Enter your last name")]
        [Display(Name = "Last Name")]
        public string rlname { get; set; }
        [Required(ErrorMessage = "Enter your email")]
        [Display(Name = "Email")]
        [DataType(DataType.EmailAddress)]
        public string remail { get; set; }
        [Required(ErrorMessage = "Password required")]
        [Display(Name = "Password")]
        [DataType(DataType.Password)]
        public string rpass { get; set; }
        [Required(ErrorMessage = "Enter your phone number")]
        [Display(Name = "Phone")]
        [DataType(DataType.PhoneNumber)]
        public string rphone { get; set; }
        public string rpic { get; set; }
    }
}
